qube_version: '2.6.1 # <<QUBE_NO_BUMP>>'
full_name: Jennifer Bödker
email: jennifer.boedker@qbic.uni-tuebingen.de
project_name: qOffer 2.0
project_short_description: qOffer assists in managing and creating offers
version: 1.0.0-SNAPSHOT
domain: portlet
language: groovy
project_slug: qOffer_2.0
project_slug_no_hyphen: qOffer_2.0
template_version: '1.0.4 # <<QUBE_NO_BUMP>>'
template_handle: portlet-groovy
github_username: jenniferboedker
creator_github_username: jenniferboedker
is_github_repo: false
is_repo_private: false
is_github_orga: false
copyright_holder: QBiC
license: MIT
main_class_prefix: qOffer
use_openbis_client: yes
use_openbis_raw_api: yes
use_qbic_databases: yes
use_vaadin_charts: yes
