qube_version: '2.4.6 # <<QUBE_NO_BUMP>>'
full_name: Jennifer Bödker
email: jennifer.boedker@qbic.uni-tuebingen.de
project_name: qoffer-2-portlet
project_short_description: qOffer assists in managing and creating offers
project_slug: qoffer-2-portlet
project_slug_no_hyphen: qoffer_2_portlet
project_short_description: qOffer assists in managing and creating offers
version: 1.0.0-SNAPSHOT
template_version: '1.0.2 # <<QUBE_NO_BUMP>>'
template_handle: portlet-groovy
github_username: qbicsoftware
creator_github_username: jenniferboedker
is_github_repo: true
is_repo_private: false
is_github_orga: true
github_orga: qbicsoftware
domain: portlet
language: groovy
copyright_holder: Jennifer Bödker
github_username: qbicsoftware
creator_github_username: jenniferboedker
main_class_prefix: qOffer
license: MIT
main_class_prefix: qOffer
use_openbis_client: no
use_openbis_raw_api: no
use_qbic_databases: no
use_vaadin_charts: no
