full_name: Sven Fillinger
email: sven.fillinger@qbic.uni-tuebingen.de
project_name: qoffer-2-portlet
project_short_description: qoffer-2-portlet. A qube based .
version: 1.0.0-SNAPSHOT
domain: portlet
language: groovy
project_slug: qoffer-2-portlet
project_slug_no_hyphen: qoffer_2_portlet
template_version: '1.0.2 # <<QUBE_NO_BUMP>>'
template_handle: portlet-groovy
github_username: qbicsoftware
creator_github_username: sven1103
is_github_repo: true
is_repo_private: false
is_github_orga: true
copyright_holder: QBiC
license: MIT
main_class_prefix: Qbic
use_openbis_client: no
use_openbis_raw_api: no
use_qbic_databases: no
use_vaadin_charts: no
